"""initial commit

Revision ID: 7f5e12c3962d
Revises: 
Create Date: 2021-07-19 16:09:01.404911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f5e12c3962d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('seg', sa.String(), nullable=True),
    sa.Column('e1', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('e2', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('e3', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('e4', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_e1'), 'paper', ['e1'], unique=False)
    op.create_index(op.f('ix_paper_e2'), 'paper', ['e2'], unique=False)
    op.create_index(op.f('ix_paper_e3'), 'paper', ['e3'], unique=False)
    op.create_index(op.f('ix_paper_e4'), 'paper', ['e4'], unique=False)
    op.create_index(op.f('ix_paper_id'), 'paper', ['id'], unique=True)
    op.create_index(op.f('ix_paper_link'), 'paper', ['link'], unique=False)
    op.create_index(op.f('ix_paper_seg'), 'paper', ['seg'], unique=False)
    op.create_index(op.f('ix_paper_title'), 'paper', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_paper_title'), table_name='paper')
    op.drop_index(op.f('ix_paper_seg'), table_name='paper')
    op.drop_index(op.f('ix_paper_link'), table_name='paper')
    op.drop_index(op.f('ix_paper_id'), table_name='paper')
    op.drop_index(op.f('ix_paper_e4'), table_name='paper')
    op.drop_index(op.f('ix_paper_e3'), table_name='paper')
    op.drop_index(op.f('ix_paper_e2'), table_name='paper')
    op.drop_index(op.f('ix_paper_e1'), table_name='paper')
    op.drop_table('paper')
    # ### end Alembic commands ###
